apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-08
spec:
  containers:
    - name: frontend
      image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
      env:
      - name: CATALOGUE_HOST
        value: "Hello from the CATALOGUE_HOST"
      - name: CATALOGUE_PORT
        value: "Hello from the CATALOGUE_PORT"
#hard coded config map
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-08
data:
  # property-like keys; each key maps to a simple value
  CATALOGUE_HOST: "3"
  CATALOGUE_PORT: "user-interface.properties"
#
#  # file-like keys
#  game.properties: |
#    enemy.types=aliens,monsters
#    player.maximum-lives=5
#  user-interface.properties: |
#    color.good=purple
#    color.bad=yellow
#    allow.textmode=true
---
#values come from configmap ref and specific config
apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-09
spec:
  containers:
    - name: frontend
      image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
      env:
        - name: CATALOGUE_HOST
          valueFrom:
            configMapKeyRef:
              name: cn-07
              key: CATALOGUE_HOST

        - name: CATALOGUE_PORT
          valueFrom:
            configMapKeyRef:
              name: cn-07
              key: CATALOGUE_PORT
---
#entier configmap
apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-10
spec:
  containers:
    - name: frontend
      image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
      envFrom:
        - configMapRef:
            name: cm-08



---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-09
data:
  cart-service: |
    [Unit]
    Description = Cart Service
    [Service]
    User=roboshop
    #Environment=REDIS_HOST=redis.{{ env }}.meppk.xyz
    Environment=REDIS_HOST={{ secrets.REDIS_HOST }}
    #Environment=CATALOGUE_HOST=catalogue.{{ env }}.meppk.xyz
    Environment=CATALOGUE_HOST={{ secrets.CATALOGUE_HOST }}
    #Environment=CATALOGUE_PORT=8080
    Environment=CATALOGUE_PORT={{ secrets.CATALOGUE_PORT }}
    ExecStart=/bin/node /app/server.js
    SyslogIdentifier=cart
    
    [Install]
    WantedBy=multi-user.target
    
    catalogue-service: |
        [Unit]
        Description = Cart Service
        [Service]
        User=roboshop
        #Environment=REDIS_HOST=redis.{{ env }}.meppk.xyz
        Environment=REDIS_HOST={{ secrets.REDIS_HOST }}
        #Environment=CATALOGUE_HOST=catalogue.{{ env }}.meppk.xyz
        Environment=CATALOGUE_HOST={{ secrets.CATALOGUE_HOST }}
        #Environment=CATALOGUE_PORT=8080
        Environment=CATALOGUE_PORT={{ secrets.CATALOGUE_PORT }}
        ExecStart=/bin/node /app/server.js
        SyslogIdentifier=cart

        [Install]
        WantedBy=multi-user.target
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-09
spec:
  containers:
    - name: debug
      image: docker.io/rkalluru/debug
      volumeMounts: #config mounting to container
        - name: config-volume
          mountPath: "/etc/config"

  volumes:
    - name: config-volume
      configMap:
        name: cm-09

