apiVersion: v1
kind: Secret
metadata:
  name: secret-09-01
data:
  extra: YmFyCg==
  #password: abcd@1234 #this is hardcoded value #convert string into base64 online
  password: YWJjZEAxMjM0

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret09-01
spec:
  containers:
    - name: debug
      image: docker.io/rkalluru/debug
      env:
        - name: password
          valueFrom:
            secretKeyRef:
              name: secret-09-01
              key: password

#kubectl exec -it pod secret-09-01 -- env