---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    appName: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    appName: frontend
spec:
  containers:
    - name: frontend
      image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
      env:
      - name: CATALOGUE_HOST
        value: "Hello from the environment"
      - name: CATALOGUE_PORT
        value: "Hello from the environment"
      - name: USER_HOST
        value: "Hello from the environment"
      - name: USER_PORT
        value: "Hello from the environment"
      - name: CART_HOST
        value: "Hello from the environment"
      - name: CART_PORT
        value: "Hello from the environment"
      - name: SHIPPING_HOST
        value: "Hello from the environment"
      - name: SHIPPING_PORT
        value: "Hello from the environment"
      - name: PAYMENT_HOST
        value: "Hello from the environment"
      - name: PAYMENT_PORT
        value: "Hello from the environment"
